version: '3.8'

services:
  postgres:
    image: stashapp/postgres:latest
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: <USER>
      POSTGRES_PASSWORD: <PASSWORD>
      POSTGRES_DB: <DATABASE>
    volumes:
      - /pgdata:/var/lib/postgresql/data

  stash-box:
    image: stashapp/stash-box:development
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    volumes:
      - <CONFIG_DIR>:/root/.stash-box
    labels:
      - traefik.http.routers.stash-box.rule=Host(`<DOMAIN>`)
      - traefik.http.routers.stash-box.tls=true
      - traefik.http.routers.stash-box.tls.certresolver=stash-box
      - traefik.port=9998

  traefik:
    image: traefik:2.3
    restart: always
    ports:
      - 80:80
      - 443:443
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.docker=true"
      - "--certificatesResolvers.stash-box.acme.email=<EMAIL>"
      - "--certificatesResolvers.stash-box.acme.storage=/acme.json"
      - "--certificatesresolvers.stash-box.acme.tlschallenge=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /traefik/acme.json:/acme.json
